routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes(['register' => false]);
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/otp-verification/{email}', [App\Http\Controllers\OtpVerificationController::class, 'email'])->name('otp-verification.email');
Route::post('/otp-verification', [App\Http\Controllers\OtpVerificationController::class, 'verify'])->name('otp-verification');
Route::group(['prefix' => 'cms', 'as' => 'cms.', 'middleware' => ['auth']], function () {
    Route::resource('branches', \App\Http\Controllers\Cms\BranchController::class);
    Route::resource('branch-departments', \App\Http\Controllers\Cms\BranchDepartmentController::class);
    Route::resource('settings', \App\Http\Controllers\Cms\SettingController::class);
    Route::resource('emps', \App\Http\Controllers\Cms\EmpController::class);
    Route::resource('clients', \App\Http\Controllers\Cms\ClientController::class);
    Route::resource('invoices', \App\Http\Controllers\Cms\InvoicesController::class);
    Route::resource('leads', \App\Http\Controllers\Cms\LeadController::class);
    Route::resource('consultant-bonuses', \App\Http\Controllers\Cms\ConsultantBonusController::class);
    Route::resource('staff-consultant-bonuses', \App\Http\Controllers\Cms\StaffConsultantBonusController::class);
    Route::resource('lead-consultant-bonuses', \App\Http\Controllers\Cms\LeadConsultantBonusController::class);
    Route::resource('service-groups', \App\Http\Controllers\Cms\ServiceGroupController::class);
    Route::resource('service-items', \App\Http\Controllers\Cms\ServiceItemController::class);
    Route::resource('teams', \App\Http\Controllers\Cms\TeamController::class);
    Route::resource('team-members', \App\Http\Controllers\Cms\TeamMemberController::class);
    Route::resource('projects', \App\Http\Controllers\Cms\ProjectController::class);
});

resources/views/cms/team-member/create/parts/form/create.blade.php
<form id="form-create-team-member" method="POST" action="{{ route('api.cms.team-member.store') }}">
    <input id="team_id" name="team_id" type="hidden" class="form-control">
    <input id="emp_id" name="emp_id" type="hidden" class="form-control">
    <div class="row mb-4">
        <label class="col-sm-3 col-form-label">Team Name</label>
        <div class="col-sm-9">
            <input id="team_name" type="text" class="form-control" readonly required>
        </div>
    </div>
    <div class="row mb-4">
        <label class="col-sm-3 col-form-label">Branch</label>
        <div class="col-sm-9">
            <input id="branch_name" type="text" class="form-control" readonly required>
        </div>
    </div>
    <div class="row mb-4">
        <label class="col-sm-3 col-form-label">Department</label>
        <div class="col-sm-9">
            <input id="department_name" type="text" class="form-control" readonly required>
        </div>
    </div>
    <div class="row mb-4">
        <label class="col-sm-3 col-form-label">Employee</label>
        <div class="col-sm-9">
            <input id="employee_name" type="text" class="form-control" readonly required>
        </div>
    </div>
    <div class="row justify-content-end">
        <div class="col-sm-9">
            <div>
                <a class="btn btn-dark w-md" href="{{ route('cms.team-members.index') }}">Back</a>
                <button type="button" class="btn btn-secondary w-md" data-bs-toggle="modal" data-bs-target="#modal-table-team">Select Team</button>
                <button type="button" class="btn btn-secondary w-md" data-bs-toggle="modal" data-bs-target="#modal-table-emp-occupation">Select Employee</button>
                <button type="submit" class="btn btn-primary w-md">Save</button>
            </div>
        </div>
    </div>
    <div style="display: none" class="spinner-border text-primary m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</form>